[PHP]
memory_limit = 2048M
upload_max_filesize = 64M
post_max_size = 64M
date.timezone = Europe/Prague
; mail() zakazujeme - všechny e-maily musí jít přes SMTP do Mailpitu (mailpit:1025)
disable_functions = mail
